### ISSUE TITLE
Questions about the paper

### ISSUE THREAD

**Issue by junmeiRong** [fatimahkj/EBF#1]
I read your paper, and I have some questions, what is the seed provided by BMC to the Fuzzer?
What exactly does the seed refer to?
looking forward to your reply

**Comment by fatimahkj** [comment]
Hi, 

The seeds are the values extracted from the BMC counter-example (non-deterministic values) 
Let us say we have the following code:

```
void foo(void * arg){
int a = __VERIFIER_nondet_int();
int b = __VERIFIER_nondet_int(); 
if((a + b) == 42) reach_error();
}
int main() {
pthread_t t1, t2;
pthread_create(&t1, 0, foo, 0);
pthread_create(&t2, 0, foo, 0);
pthread_join(t1, 0);
pthread_join(t2, 0);
}
```
When we verify this code with ESBMC, ESBMC will produce values for `a` and `b ` (non-deterministically) and produce a counter-example as the following. 

![image](https://user-images.githubusercontent.com/47563480/237043504-dbd33937-341a-4c6c-8b23-30169b6aae0b.png)


The values we extract from this example are 42 and 0, which will reach the statement `reach_error()` and make the program fails.
We save those values in a file in an input directory for the fuzzer. (uses as a corpus for the fuzzer)

The fuzzer requires seeds to start fuzzing the program, and we provide him with these initial seeds to start fuzzing.


I hope I answered your question clearly, and if you have more questions, do not hesitate to ask. 

For EBF presentation:
[ EBF presentation](https://www.youtube.com/watch?v=cUK1mcuvusI&list=WL&index=22)

**Comment by junmeiRong** [comment]
Thank you very much for your reply and the link video provided.
